VentaSnacks/Controllers/FacturasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VentaSnacks.Models;

namespace VentaSnacks.Controllers
{
    public class FacturasController : Controller
    {
        private VentaSnackEntities1 db = new VentaSnackEntities1();

        // GET: Facturas
        public ActionResult Index()
        {
            if (TempData.ContainsKey("mensaje"))
            {
                ViewBag.Mensaje = TempData["mensaje"].ToString();
            }

            var facturas = db.Facturas.Include(f => f.Cliente).Include(f => f.Estado).Include(f => f.TipoPago);
            return View(facturas.ToList());
        }

        // GET: Facturas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Factura factura = db.Facturas.Find(id);
            if (factura == null)
            {
                return HttpNotFound();
            }
            return View(factura);
        }

        // GET: Facturas/Create
        public ActionResult Create()
        {
            if (TempData.ContainsKey("mensaje"))
            {
                ViewBag.Mensaje = TempData["mensaje"].ToString();
            }

            ViewBag.idCliente = new SelectList(db.Clientes, "idCliente", "nombre");
            ViewBag.idEstado = new SelectList(db.Estadoes, "idEstado", "nombre");
            ViewBag.idTipoPago = new SelectList(db.TipoPagoes, "idTipoPago", "nombre");
            List<VentaSnacks.Models.Linea> obj = (List<VentaSnacks.Models.Linea>)Session["listaArticulos"];
            ViewBag.listaLineas = obj;
            VentaSnacks.Models.Factura f = new VentaSnacks.Models.Factura();
            ViewData["Subtotal"] = f.subtotal(obj).ToString("0.00");
            ViewData["Descuento"] = f.descuento(Convert.ToDecimal(ViewData["Subtotal"]), Convert.ToDecimal(0)).ToString("0.00");
            ViewData["Impuestos"] = f.impuestos(Convert.ToDecimal(ViewData["Subtotal"]), Convert.ToDecimal(ViewData["Descuento"])).ToString("0.00");
            ViewData["Total"] = f.total(Convert.ToDecimal(ViewData["Subtotal"]), Convert.ToDecimal(ViewData["Descuento"]), Convert.ToDecimal(ViewData["Impuestos"])).ToString("0.00");
            ViewData["AplicaDescuento"] = f.aplicadescuento(obj);

            return View();
        }



        // POST: Facturas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Factura factura)
        {

            if (TempData.ContainsKey("mensaje"))
            {
                ViewBag.Mensaje = TempData["mensaje"].ToString();
            }
            //Lista los articulos del carro de compras
            List<VentaSnacks.Models.Linea> obj = (List<VentaSnacks.Models.Linea>)Session["listaArticulos"];
            List<VentaSnacks.Models.Linea> l = obj;

            if (ModelState.IsValid)
            {



                //No permite facturar si la lista de articulos es 0
                if (obj.Count != 0)
                {
                   

                    //Calcula los montos
                    decimal subtotal = factura.subtotal(obj);
                    decimal descuento = factura.descuento(subtotal, Convert.ToDecimal(factura.porcentajeDesc));
                    decimal impuestos = factura.impuestos(subtotal, descuento);
                    decimal tot = factura.total(subtotal, descuento, impuestos);

                    //Agrega los datos de la factura
                    factura.idEstado = 0;
                    factura.Total = tot;
                    factura.fecha = DateTime.Now;



                    factura.Lineas = obj;

                    factura.guardar(factura);
                    Session["listaArticulos"] = new List<VentaSnacks.Models.Linea>();
                    factura = factura.ultFactura();
                    return RedirectToAction("Pagar", routeValues: new { id = factura.idFactura });


                }

                TempData["mensaje"] = "Debe seleccionar al menos 1 Articulo";
                return RedirectToAction("Create");
            }


            ViewBag.idCliente = new SelectList(db.Clientes, "idCliente", "nombre", factura.idCliente);
            ViewBag.idEstado = new SelectList(db.Estadoes, "idEstado", "nombre", factura.idEstado);
            ViewBag.idTipoPago = new SelectList(db.TipoPagoes, "idTipoPago", "nombre", factura.idTipoPago);
            ViewBag.listaLineas = obj;
            ViewData["Subtotal"] = factura.subtotal(obj).ToString("0.00");
            ViewData["Descuento"] = factura.descuento(Convert.ToDecimal(ViewData["Subtotal"]), Convert.ToDecimal(0)).ToString("0.00");
            ViewData["Impuestos"] = factura.impuestos(Convert.ToDecimal(ViewData["Subtotal"]), Convert.ToDecimal(ViewData["Descuento"])).ToString("0.00");
            ViewData["Total"] = factura.total(Convert.ToDecimal(ViewData["Subtotal"]), Convert.ToDecimal(ViewData["Descuento"]), Convert.ToDecimal(ViewData["Impuestos"])).ToString("0.00");
            ViewData["AplicaDescuento"] = factura.aplicadescuento(obj);
            return View(factura);
        }








        public ActionResult Pagar(int id)
        {

            if (TempData.ContainsKey("mensaje"))
            {
                ViewBag.Mensaje = TempData["mensaje"].ToString();
            }

            Factura factura = db.Facturas.Where(x => x.idFactura == id).FirstOrDefault();
            if (factura == null)
            {
                return HttpNotFound();
            }
            ViewBag.idCliente = new SelectList(db.Clientes, "idCliente", "nombre", factura.idCliente);
            ViewBag.idEstado = new SelectList(db.Estadoes, "idEstado", "nombre", factura.idEstado);
            ViewBag.idTipoPago = new SelectList(db.TipoPagoes, "idTipoPago", "nombre", factura.idTipoPago);
            return View(factura);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Pagar(Factura factura)
        {

            if (TempData.ContainsKey("mensaje"))
            {
                ViewBag.Mensaje = TempData["mensaje"].ToString();
            }

            if (ModelState.IsValid)
            {
                if (factura.idEstado == 0)
                {

                    factura.idEstado = 1;
                    db.Entry(factura).State = EntityState.Modified;
                    db.SaveChanges();
                    if (factura.idTipoPago == 0)
                    {
                        TempData["mensaje"] = "Se proceso su pago con tarjeta Correctamente";
                        factura.idEstado = 1;
                        db.Entry(factura).State = EntityState.Modified;
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        decimal valor = Convert.ToDecimal(Request.Form["montoCancelar"]);
                        string pagar = factura.pagaFactura(factura, valor);
                        if (pagar == "El monto no es suficiente")
                        {
                            TempData["mensaje"] = pagar;
                            return RedirectToAction("Pagar");
                        }
                        else
                        {
                            TempData["mensaje"] = pagar;
                            return RedirectToAction("Index");
                        }
                    }

                }
                else
                {
                    TempData["mensaje"] = "La Factura ya fue cancelada";
                    return RedirectToAction("Pagar");
                }


            }

            //ViewBag.idCliente = new SelectList(db.Clientes, "idCliente", "nombre", factura.idCliente);
            //ViewBag.idEstado = new SelectList(db.Estadoes, "idEstado", "nombre", factura.idEstado);
            //ViewBag.idTipoPago = new SelectList(db.TipoPagoes, "idTipoPago", "nombre", factura.idTipoPago);
            return View(factura);
        }




        // GET: Facturas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Factura factura = db.Facturas.Find(id);
            if (factura == null)
            {
                return HttpNotFound();
            }
            ViewBag.idCliente = new SelectList(db.Clientes, "idCliente", "nombre", factura.idCliente);
            ViewBag.idEstado = new SelectList(db.Estadoes, "idEstado", "nombre", factura.idEstado);
            ViewBag.idTipoPago = new SelectList(db.TipoPagoes, "idTipoPago", "nombre", factura.idTipoPago);
            return View(factura);
        }

        // POST: Facturas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idFactura,idCliente,porcentajeDesc,idEstado,Total,idTipoPago,fecha")] Factura factura)
        {
            if (ModelState.IsValid)
            {
                db.Entry(factura).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idCliente = new SelectList(db.Clientes, "idCliente", "nombre", factura.idCliente);
            ViewBag.idEstado = new SelectList(db.Estadoes, "idEstado", "nombre", factura.idEstado);

VentaSnacks/Controllers/LineasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VentaSnacks.Models;

namespace VentaSnacks.Controllers
{
    public class LineasController : Controller
    {
        private VentaSnackEntities1 db = new VentaSnackEntities1();

        // GET: Lineas
        public ActionResult Index()
        {
            var lineas = db.Lineas.Include(l => l.Articulo);
            return View(lineas.ToList());
        }

        // GET: Lineas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Linea linea = db.Lineas.Find(id);
            if (linea == null)
            {
                return HttpNotFound();
            }
            return View(linea);
        }

        // GET: Lineas/Create
        public ActionResult Create()
        {
            if (TempData.ContainsKey("mensaje"))
            {
                ViewBag.Mensaje = TempData["mensaje"].ToString();
            }

            List<Articulo> lista = db.Articuloes.ToList();
            ViewBag.listaProductos = lista;
            Linea l = new Linea();
            return PartialView(l);
        }

        // POST: Lineas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Linea linea)
        {
            //Mensaje
            if (TempData.ContainsKey("mensaje"))
            {
                ViewBag.Mensaje = TempData["mensaje"].ToString();
            }

            if (ModelState.IsValid)
            {
                if (linea.cantidad>0)
                {
                Articulo art = obtenerArticulo(linea);

                linea.Articulo = art;
                List<VentaSnacks.Models.Linea> obj = (List<VentaSnacks.Models.Linea>)Session["listaArticulos"];
                Linea remover = null;
                foreach (var li in obj)
                {
                    if (linea.idArticulo==li.idArticulo)
                    {
                        linea.cantidad += li.cantidad;
                        remover = li;
                    }
                }
                obj.Remove(remover);
                linea.total = Decimal.Round(art.TotalLinea(linea),2);
                obj.Add(linea);
                Session["listaArticulos"] = obj;
                TempData["mensaje"] = "Se Agregaron:  "+linea.cantidad+" - "+linea.Articulo.nombre;
                return RedirectToAction("Create");


                }
                else
                {
                    TempData["mensaje"] = "La cantidad seleccionada debe ser mayor a 0";
                    return RedirectToAction("Create");
                }
            }

            ViewBag.idArticulo = new SelectList(db.Articuloes, "idArticulo", "nombre", linea.idArticulo);
            return View(linea);
        }

        // GET: Lineas/Seleccionar
        public ActionResult Seleccionar()
        {
            if (TempData.ContainsKey("mensaje"))
            {
                ViewBag.Mensaje = TempData["mensaje"].ToString();
            }

            List<Articulo> lista = db.Articuloes.ToList();
            ViewBag.listaProductos = lista;
            Linea l = new Linea();
            return View(l);
        }

        // POST: Lineas/Seleccionar
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Seleccionar(Linea linea)
        {
            if (TempData.ContainsKey("mensaje"))
            {
                ViewBag.Mensaje = TempData["mensaje"].ToString();
            }

            if (ModelState.IsValid)
            {
                Articulo art = obtenerArticulo(linea);
                linea.Articulo = art;
                linea.total = art.TotalLinea(linea);
                db.Lineas.Add(linea);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.idArticulo = new SelectList(db.Articuloes, "idArticulo", "nombre", linea.idArticulo);
            return View(linea);
        }


        // GET: Lineas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Linea linea = db.Lineas.Find(id);
            if (linea == null)
            {
                return HttpNotFound();
            }
            ViewBag.idArticulo = new SelectList(db.Articuloes, "idArticulo", "nombre", linea.idArticulo);
            return View(linea);
        }

        // POST: Lineas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idLinea,idArticulo,cantidad,total")] Linea linea)
        {
            if (ModelState.IsValid)
            {
                db.Entry(linea).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idArticulo = new SelectList(db.Articuloes, "idArticulo", "nombre", linea.idArticulo);
            return View(linea);
        }

        // GET: Lineas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Linea linea = db.Lineas.Find(id);
            if (linea == null)
            {
                return HttpNotFound();
            }
            return View(linea);
        }

        // POST: Lineas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Linea linea = db.Lineas.Find(id);
            db.Lineas.Remove(linea);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public Articulo obtenerArticulo(Linea lin)
        {
            Articulo l = db.Articuloes.Where(x => x.idArticulo == lin.idArticulo).FirstOrDefault();

            return l;
        }
    }
}

VentaSnacks/Views/Facturas/Create.cshtml
@model VentaSnacks.Models.Factura
@{
    <link href="~/Content/StyleP.css" rel="stylesheet" />
    ViewBag.Title = "Crear";
    Layout = "~/Views/Shared/_Layout.cshtml";
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    @*<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">*@
    <link href="~/Content/Personalizado.css" rel="stylesheet" />
    <link href="~/Content/smart_wizard_vertical.css" rel="stylesheet" />
    <script src="~/Scripts/popper.min.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/jquery-3.4.1.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>

}
@if ((VentaSnacks.Models.User)Session["usuario."] == null)
{
    Response.Redirect("~/Users/Login");
}
<div class="fondo">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <br />
        <h2>Nueva Factura</h2>
        <br />
        <br />
        <div class="contenedor">
            <table id="tablaFactura" style="min-width:500px;">
                @*<tr>
                <td>Seleccionar Cliente: <input type="checkbox" name="checkCliente" id="checkCliente" value="1" onchange="javascript:showContent()" /></td>
                <td></td>
            </tr>*@
                <tr id="clientes">

                    <td>Cliente: </td>
                    <td>
                        @Html.DropDownList("idCliente", null, "Cliente Contado", htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.idCliente, "", new { @class = "text-danger" })

                    </td>
                </tr>
                <tr>
                    <th>Productos: </th>
                    <th>
                        @Html.ActionLink("Agregar Productos", "Create", "Lineas")
                    </th>
                </tr>

                <tr>
                    <td colspan="2">
                        <br />
                        @if (ViewBag.listaLineas.Count != 0)
                        {
                            <table class="table-secondary" style="width:100%">
                                <tr style="text-align:center">
                                    <th>
                                        <h5>Nombre</h5>
                                    </th>
                                    <th>
                                        <h5>Cantidad</h5>
                                    </th>
                                    <th>
                                        <h5>Total</h5>
                                    </th>
                                </tr>

                                @foreach (var lin in ViewBag.listaLineas)
                                {
                                    <tr style="text-align:center">
                                        <td>
                                            <h6>@lin.Articulo.nombre</h6>
                                        </td>
                                        <td>
                                            <h6>@lin.cantidad</h6>
                                        </td>
                                        <td style="text-align:right">
                                            <h6>₡ @lin.total</h6>
                                        </td>
                                    </tr>
                                }

                            </table>
                        }
                        else
                        {
                            <h4 style="color:orangered">No hay Productos Seleccionados</h4>
                        }

                        <br />
                    </td>
                </tr>



                @if ((Boolean)ViewData["AplicaDescuento"] == true)
                {
                    <tr>
                        <td>Descuento: </td>
                        <td>
                            @Html.EditorFor(model => model.porcentajeDesc, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.porcentajeDesc, "", new { @class = "text-danger" })
                        </td>
                    </tr>
                }
                <tr>
                    <td>SubTotal: </td>
                    <td style="text-align:right">
                        <div class="col-md-10">
                            <h6>₡ @ViewData["Subtotal"]</h6>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>Descuento: </td>
                    <td style="text-align:right">
                        <div class="col-md-10">
                            <h6>₡ @ViewData["Descuento"]</h6>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>Impuestos: </td>
                    <td style="text-align:right">
                        <div class="col-md-10">
                            <h6>₡ @ViewData["Impuestos"]</h6>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>Total: </td>
                    <td style="text-align:right">
                        <div class="col-md-10">
                            <h5>₡ @ViewData["Total"]</h5>
                        </div>
                    </td>
                </tr>

                <tr>
                    <td colspan="2">
                        <hr />
                    </td>
                </tr>
                <tr>
                    <td>Tipo de Pago</td>
                    <td>
                        @Html.DropDownList("idTipoPago", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.idTipoPago, "", new { @class = "text-danger" })
                    </td>
                </tr>
                <tr>
                    <td colspan="2"><hr /></td>
                </tr>
                <tr style="text-align:center">
                    <td>
                        <div>
                            @Html.ActionLink("Regresar", "Index", "Home")
                        </div>
                    </td>
                    <td>
                        <br />
                        <div class="col-md-offset-2 col-md-10">
                            <button type="submit" class="btn btn-primary" data-dismiss="modal">Pagar</button>
                        </div>
                        <br />
                    </td>
                </tr>
            </table>
            <br />

        </div>






    }



</div>








@section Scripts {
    <script type="text/javascript">
        function showContent() {
            element = document.getElementById("clientes");
            check = document.getElementById("chkSeleccion");
            if (check.checked) {
                element.style.display = 'block';
            }
            else {
                element.style.display = 'none';
            }
        }</script>



}

VentaSnacks/Views/Facturas/Delete.cshtml
@model VentaSnacks.Models.Factura

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Factura</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.porcentajeDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.porcentajeDesc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Total)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Total)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fecha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fecha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cliente.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cliente.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estado.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoPago.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoPago.nombre)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

VentaSnacks/Views/Facturas/Details.cshtml
@model VentaSnacks.Models.Factura

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Factura</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.porcentajeDesc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.porcentajeDesc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Total)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Total)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fecha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fecha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cliente.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cliente.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estado.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoPago.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoPago.nombre)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.idFactura }) |
    @Html.ActionLink("Back to List", "Index")
</p>

VentaSnacks/Views/Facturas/Edit.cshtml
@model VentaSnacks.Models.Factura

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Factura</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.idFactura)

        <div class="form-group">
            @Html.LabelFor(model => model.idCliente, "idCliente", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idCliente", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idCliente, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.porcentajeDesc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.porcentajeDesc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.porcentajeDesc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.idEstado, "idEstado", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idEstado", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idEstado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Total, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Total, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Total, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.idTipoPago, "idTipoPago", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idTipoPago", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idTipoPago, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fecha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fecha, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fecha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}